### ISSUE TITLE
[Read This]: Destructuring Form props gives a "Cannot update a component (`ForwardRef(ke)`)" error

### ISSUE THREAD

**Issue by nordowl** [houseform/houseform#102]
### Steps To Reproduce

1. Create a form using the `Form` component
2. Create a child component and pass all of `Form`'s props to it
3. Use these props in the child component

### Expected Behavior

No warning in console, as everything works as expected.

### Reproduction link

https://github.com/nordowl/houseform-setstate-in-render

### HouseForm Version

1.10.0

### React Version

18.2.0

### Environment

Browser (Chrome/Firefox/Safari/etc)

### More details

Stack trace using the reproduction repo

```
InnerForm@webpack-internal:///(app-client)/./app/page.tsx:34:66
ke@webpack-internal:///(app-client)/./node_modules/houseform/dist/houseform.js:95:81
div
Page
ScrollAndFocusHandler@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:153:1
InnerLayoutRouter@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:196:44
RedirectErrorBoundary@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:361:9
RedirectBoundary@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:368:25
NotFoundErrorBoundary@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:397:9
NotFoundBoundary@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:404:53
LoadingBoundary@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:317:64
ErrorBoundary@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:72:56
RenderFromTemplateContext@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/render-from-template-context.js:12:34
OuterLayoutRouter@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:23:177
body
html
ReactDevOverlay@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:61:9
HotReload@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:20:39
Router@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:48:89
ErrorBoundaryHandler@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:59:9
ErrorBoundary@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:72:56
AppRouter@webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:24:39
ServerRoot@webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:147:25
RSCComponent
Root@webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:164:25
```

**Comment by joaom00** [comment]
Interesting, using like this:

```tsx
{(props) => <InnerForm formProps={{ ...props }} />}
```

will not throw that error :thinking: https://stackblitz.com/edit/houseform-v1-example-vfywou?file=App.tsx

**Comment by nordowl** [comment]
Huh, weird. I tested this in my project where that error first occurred and spreading the props does fix it.

**Comment by crutchcorn** [comment]
This is the unfortunate side effect of some of our performance trickery.

See, to avoid having to recompute every value (IE: `FormInstance.value` is a very expensive operation) we use getters on the FormInstance:

https://github.com/houseform/houseform/blob/main/lib/form/form.tsx#L416-L436

By destructuring, you're telling `Form` "I want all of the props, but only assign two of them to a variable", which in turn runs a `setState` outside of the `Form` component, which React does not allow.

To fix this issue, replace:

```jsx
const { isValid, errors } = formProps;
```

```jsx
const isValid = formProps.isValid;
const errors = formProps.errors;
```

I don't think there is a way we can sidestep this with the library, unfortunately :/ What we _might_ be able to do is add in a rule with ESLint that helps catch and prevent these disallowed/discouraged destructures.

**Comment by nordowl** [comment]
Thanks for clarifying!
