### ISSUE TITLE
[Feature Request]: Field strong typed names

### ISSUE THREAD

**Issue by Jonatthu** [houseform/houseform#105]
### Description

react-hook-form checks for the names to actually exist when declaring a new name on a field, if the typescript FormType changes one property name or removes it, the <Field name="no_more_valid_name" /> should start erroring out since the FormType typescript is no longer having that field name. 

### Describe the solution you'd like

Maybe 
```
<Form<FormType> /* ... */>
{(form) => (
    <Field 
        name="no_more_valid_name" 
        initialValue={0} 
        form={form} 
              /** form infers the keys of the FormType and 
                 validates that the name property exist on that type, 
                 also infers the initialValue type */ 
     />
)}
</Form>
```

### Describe alternatives you've considered

Make form optional to not break previous people using this.

**Comment by crutchcorn** [comment]
Truth be told, I really don't know how I feel about this.

I'm not sure I see a benefit to this API when you can do:

```
<Form<FormType> /* ... */>
{(form) => (
    <Field<FormType['no_more_valid_name']>
        name="no_more_valid_name" 
        initialValue={0} 
     />
)}
</Form>
```

And get an error that way. @joaom00 what do you think?

**Comment by joaom00** [comment]
I agree, and what @crutchcorn suggested is more straightforward

**Comment by Jonatthu** [comment]
@crutchcorn @joaom00 this allows typos, which is one of the things houseform is supposed to be great for is deep integration with zod and typescript tho.
<img width="357" alt="Screenshot 2023-04-08 at 6 34 09 PM" src="https://user-images.githubusercontent.com/3742176/230749751-c215651a-0099-4720-bf03-9fd0da04d248.png">

**Comment by crutchcorn** [comment]
https://github.com/microsoft/TypeScript/issues/14729

I _think_ we might be able to pass this without adding a `form` field

**Comment by Jonatthu** [comment]
@crutchcorn yeah ether way, as long there is an autocomplete string on name and also becomes an error to have a typo, also without repeating too much ourselves like setting the type or double names. Like the example I gave if you already giving a type to the parent form I should not need to do something like

'''

<Field<FormType["userName"]> name="userName"
'''

Instead just

'''
<Field name="userName">
'''

Including the typing benefits

**Comment by Jonatthu** [comment]
@crutchcorn @joaom00 

This is how I do it with react hook form:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/3742176/230782759-07e7b449-b377-4395-8647-4964d582d37e.png">

**Comment by crutchcorn** [comment]
I think we're closing this as a "not fix"
