### ISSUE TITLE
[Bug]: reset() and isDirty not working correctly with FieldArrayItem

### ISSUE THREAD

**Issue by nordowl** [houseform/houseform#107]
### Steps To Reproduce

I found multiple smaller issues when using `reset()` with `FieldArrayItem`s. I've created two slightly different Stackblitz demos for testing.

### 1.
1. Go to https://stackblitz.com/edit/houseform-v1-example-7ebtfx?embed=1&file=App.tsx
2. Change the T-Shirt input value to `19.9`
3. Click the reset *button*
4. Form gets submitted (shouldn't happen), field correctly gets reset to `19.99` but `isDirty` stays `true` (should be `false`). Resetting again will set `isDirty` to `false` but it won't change again to `true` if you then modify any value
5. Repeat step 2
6. Click the reset *div*
7. Field correctly gets reset to `19.99` but `isDirty` stays `true` (should be `false`). Also there will appear some unexplainable errors but maybe I did configure something wrongly. Resetting again will set `isDirty` to `false` but it won't change again to `true` if you then modify any value

### 2.
1. Go to https://stackblitz.com/edit/houseform-v1-example-xtdvge?embed=1&file=App.tsx
4. Change the T-Shirt input value to `19.9`
5. Click the reset *button*
6. Form gets submitted (shouldn't happen), field wrongly gets reset to `19.9` and `isDirty` stays `true` (should be `false`). Resetting again will set `isDirty` to `false` but it won't change again to `true` if you then modify any value
7. Repeat step 2
8. Click the reset *div*
9. Field wrongly gets reset to `19.9` and `isDirty` stays `true` (should be `false`). Also there will appear some unexplainable errors but maybe I did configure something wrongly. Resetting again will set `isDirty` to `false` but it won't change again to `true` if you then modify any value
10. Change the T-Shirt input value to `42` or any other number value
11. Reset using either the button or the div
12. Field will reset with value `4` instead of `19.99` (removing `value: formValue` in line 24 fixes this problem for whatever reason)

### 3.
1. Go to any of the above linked Stackblitz
2. Click the reset *div*
3. Validation will happen and `isDirty` will be `true` without having changed any values

### Expected Behavior

- `isDirty` is handeled correctly
- Fields get reset correctly
- Validation doesn't happen when resetting
- Button without `type=submit` shouldn't submit the form

### Reproduction link

See above

### HouseForm Version

1.10.4

### React Version

18.2.0

### Environment

Browser (Chrome/Firefox/Safari/etc)

**Comment by crutchcorn** [comment]
It's worth mentioning that an HTML button has the `type="submit"` by default. This is why you're seeing errors with the form submitting when it shouldn't.

To fix this, change the reset button to `type="button"`. 

Outside of that, however - there's absolutely some stuff going on. Let me investigate based off of your work and see if I can't fix them.

**Comment by crutchcorn** [comment]
Alright, after investigating further, there are three distinct "bugs" being reported here:

1) The `type="button"` documented above
2) A series of valid HouseForm bugs that were not working properly with `FieldArrayItem` that have since been fixed in this PR (pending review):

     #108

3) Your report of a broken `resetWithValue` property is actually the intended (albeit confusing) behavior of HouseForm.

     See, to avoid issues with `resetWithValue` on `FieldArrayItem` and other sub-forms, we start by resetting each individual field at their "deepest" possible path first. IE:

     - `fieldOne.subField.one` is reset
     - `fieldOne.subField` is reset
     - `fieldOne` is reset

     Because of this, what's happening is that your `FieldArrayItem`s are being reset, but then the `FieldArray` is being reset with the `initialValue` of `FieldArrayItem`, which is the original array.

    To solve this, replace:

```jsx
       <FieldArray<{ name: string; price: number }>
            name="products"
            initialValue={products}
```

With:
    
```jsx
       <FieldArray<{ name: string; price: number }>
            name="products"
            initialValue={products}
            resetWithValue={formValue["products"]}
```

**Comment by nordowl** [comment]
> Your report of a broken resetWithValue property is actually the intended (albeit confusing) behavior of HouseForm.

Ah, I see. Thanks for pointing that out.
