### ISSUE TITLE
[Feature Request]: Support preserving unrendered fields' values

### ISSUE THREAD

**Issue by crutchcorn** [houseform/houseform#45]
### Description

Right now in, say, a multi-part form; you might have a series of fields you want to unrender but preserve their values.

### Describe the solution you'd like

To support this usecase, we might want to introduce an API that looks something like:

```
<Field preserveValue={true}>
```

As well as a method for eventually deleting these fields should need-be:

```
formRef.current.deleteField("name");
```

### Describe alternatives you've considered

It _might_ also be nice to have a `<Form initialValues={{name: ""}}>` syntax to pre-emptively place values in non-rendered fields but this is likely overly challenging to implement and goes against our field-first API

**Comment by joaom00** [comment]
I would like to work on it! 

I have a doubt if it would be possible to transform `formFields` into a `Map` to simplify some operations. Would this affect perf somehow?
