### ISSUE TITLE
[Feature Request]: Clear, Reset form state, value, error.

### ISSUE THREAD

**Issue by Jonatthu** [houseform/houseform#62]
### Description

Easy way to reset/clear the form once submitted.

```
onSubmit={async (values, form) => {
  await postCreateMutation.mutateAsync({ title: values.title, content: valu.es.content });
  await postAllQuery.refetch();
  form.reset(); // This does not exist!
}}
```

form.reset(); should clear all errors or state of the form and fields in general.

**Comment by crutchcorn** [comment]
Oh, like a way to set the fields back to a blank/initial state?

This seems reasonable. One question tho - how would you imagine onMountValidate to work with this functionality?

**Comment by Jonatthu** [comment]
I do not know, I just consider this a basic functionality that I use from react hook form haha, I am trying to migrate to this library but this is the first thing I have noticed does not exist @crutchcorn

**Comment by crutchcorn** [comment]
Fair enough. I'd go ahead and say that any `onMountValidate` validations should run on form reset as well. I'll mark as `good first issue` in case anyone wants to pick this up.

**Comment by crutchcorn** [comment]
Hey @Jonatthu, since this is a blocking interaction in your app, you might give this workaround a shot:

```tsx
onSubmit={(values, form) => {
  // Do your actions here...

  /** This resets the form, but does not re-run onMountValidate **/
  form.formFieldsRef.current.forEach((field) => {
    const isFieldArray = (val: any): val is FieldArrayInstance => {
      return !!(val as FieldArrayInstance).setValues;
    };
    if (isFieldArray(field)) {
      field.setValues(field.props.initialValue || []);
    } else {
      field.setValue(
        field.props.initialValue ||
          ("" as never as typeof field.props.initialValue)
      );
    }
  });
}}
```

It only works on [the brand newly released `1.4.0` of HouseForm](https://github.com/crutchcorn/houseform/releases/tag/v1.4.0) (which I updated specifically to make this temporary workaround function for now).

This won't run `onMountValidate` like the _real_ `form.reset` function, but that work depends on #38 to be implemented first.

Could you give this workaround a shot and see if it fits your needs for now?

**Comment by Jonatthu** [comment]
@crutchcorn  I think something is wrong with the types tho
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/3742176/226691895-a23b6f1e-dff1-49b1-a91c-8ee32a612f96.png">

**Comment by Jonatthu** [comment]
Also it resets the values but not the state
<img width="413" alt="image" src="https://user-images.githubusercontent.com/3742176/226697005-505aca28-f34a-4c2b-8d0d-9f56cbf6f6d9.png">

**Comment by crutchcorn** [comment]
@Jonatthu which version of HouseForm are you using? That workaround requires at least v1.4.0 of HouseForm

In regards to the state issue, try moving the `setError` to after the `setValue`, as `setValue` will trigger `onChangeValidate` validation

**Comment by Jonatthu** [comment]
Never mind the types are correct on 1.5.1 but getting the errors @crutchcorn, I can wait anyways for @ShooTeX  reset or clear method!
