### ISSUE TITLE
[Feature Request]: Ability to see state changes at a form level

### ISSUE THREAD

**Issue by roxworks** [houseform/houseform#79]
### Description

Right now you can only access the part of the form you are contextually in, such as the current fieldarray.
However, if you want to use the entire form state at once, there isn't an easy way to do that.

EX: 
I have a form that builds out a rule, then writes out the rule in english.

It has two main parts, Conditions and Actions, which are each FieldArrays

At the top of the form I write out a sentence in english based on all the conditions and actions.

However, I can't easily have the sentence update based on both the conditions state variable and the actions state variable, as I can only access one or the other depending on where I move the sentence.

### Describe the solution you'd like

Either a state variable representing the entire form, or an external way to access the state variables outside of the form, instead of just the current value of it.

Or some onStateChanged event handler for any given field/array.

**Comment by crutchcorn** [comment]
This will be solved via #56

**Comment by joaom00** [comment]
I will close the issue as I think it was solved by #56. @roxworks feel free to follow up though if you think your usecase was not covered
